from dotenv import load_dotenv
import os

load_dotenv()

KAFKA_URL = os.getenv("KAFKA_URL")
KAFKA_EMBED_TOPIC = os.getenv("KAFKA_EMBED_TOPIC")
KAFKA_EMBED_RESULT_TOPIC = os.getenv("KAFKA_EMBED_RESULT_TOPIC")
KAFKA_QUESTION_TOPIC = os.getenv("KAFKA_QUESTION_TOPIC")
KAFKA_ANSWER_TOPIC = os.getenv("KAFKA_ANSWER_TOPIC")

EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL")
EMBEDDING_DEVICE = os.getenv("EMBEDDING_DEVICE")
EMBEDDING_INDEX_PATH = os.getenv("EMBEDDING_INDEX_PATH")

LLM_API_URL = os.getenv("LLM_API_URL")
LLM_MODEL = os.getenv("LLM_MODEL")
LLM_TEMPERATURE = float(os.getenv("LLM_TEMPERATURE"))
LLM_MAX_TOKENS = int(os.getenv("LLM_MAX_TOKENS"))